version: '3.8'

services:
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: kitahkitah/foodgram_backend:latest
    restart: on-failure
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python3 manage.py migrate --no-input &&
            python3 manage.py collectstatic --no-input &&
            gunicorn backend.wsgi:application --bind 0:8000"

  frontend:
    image: kitahkitah/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.23.1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
