# Generated by Django 4.0.7 on 2022-09-08 09:15

from django.db import migrations
import recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_alter_tag_color_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.HEXColor(max_length=7, unique=True, verbose_name='цвет в HEX'),
        ),
    ]
