# Generated by Django 4.0.7 on 2022-09-09 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_Add_Subscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(related_name='subscribed_by', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
