# Generated by Django 4.0.7 on 2022-09-10 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_Move_subscriptions_to_User_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribed_by', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
